"""Generate a self-contained Manim ThreeDScene from a scene graph.

The scene file is written on every pipeline run (so anyone with manim can
render later); rendering is attempted only on request and only when manim is
importable. Rendering shells out to `python -m manim` — manim is an optional
extra (`pip install simagent[viz]`), plus ffmpeg for video output.
"""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

from ..sandbox import scene as scene_mod

_TEMPLATE = '''"""Auto-generated by SimAgent for problem: __PROBLEM_ID__

Render a rotating 3D video:   manim -qm __FILE_NAME__ ConjectureScene
Render a still frame (PNG):   manim -s -qh __FILE_NAME__ ConjectureScene
"""
from manim import *
import json
import numpy as np

SCENE = json.loads(r"""__SCENE_JSON__""")
TITLE = __TITLE__
CENTER = np.array(__CENTER__)
SCALE = __SCALE__


def T(p):
    return (np.array(p, dtype=float) - CENTER) * SCALE


class ConjectureScene(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=65 * DEGREES, theta=-45 * DEGREES)
        axes = ThreeDAxes(
            x_range=[-3, 3, 1], y_range=[-3, 3, 1], z_range=[-3, 3, 1],
            x_length=6, y_length=6, z_length=6,
        ).set_opacity(0.25)
        self.add(axes)
        labels = []
        for prim in SCENE:
            kind = prim["type"]
            color = ManimColor(prim.get("color", "#1c1e21"))
            if kind == "points":
                for p in prim["coords"]:
                    self.add(Dot3D(point=T(p), color=color,
                                   radius=max(0.06, prim.get("radius", 0.05) * SCALE)))
            elif kind == "segments":
                for a, b in prim["pairs"]:
                    self.add(Line3D(T(a), T(b), color=color,
                                    thickness=0.008 * prim.get("width", 2.0)))
            elif kind == "polygon":
                poly = Polygon(*[T(p) for p in prim["coords"]])
                poly.set_fill(color, opacity=prim.get("opacity", 0.35))
                poly.set_stroke(color, width=1.5, opacity=0.9)
                self.add(poly)
            elif kind == "mesh":
                verts = prim["vertices"]
                for face in prim["faces"]:
                    tri = Polygon(*[T(verts[i]) for i in face])
                    tri.set_fill(color, opacity=prim.get("opacity", 0.3))
                    tri.set_stroke(color, width=0.5, opacity=0.6)
                    self.add(tri)
            elif kind == "sphere":
                ball = Sphere(radius=prim["radius"] * SCALE, resolution=(24, 12))
                ball.set_color(color)
                ball.set_opacity(prim.get("opacity", 0.12))
                ball.move_to(T(prim["center"]))
                self.add(ball)
            elif kind == "label":
                labels.append(prim["text"])
        title = Text(TITLE, font_size=26)
        title.to_corner(UL)
        self.add_fixed_in_frame_mobjects(title)
        if labels:
            sub = Text(" | ".join(labels), font_size=18)
            sub.to_corner(DL)
            self.add_fixed_in_frame_mobjects(sub)
        self.begin_ambient_camera_rotation(rate=0.25)
        self.wait(8)
'''


def _manim_python() -> str | None:
    """Interpreter that can run `-m manim`.

    Resolution order: SIMAGENT_MANIM_PYTHON env var; this interpreter (if manim
    is importable); a repo-local `.manim-env` conda env (created without sudo
    via micromamba — see README) next to the cwd or the repo root.
    """
    env = os.environ.get("SIMAGENT_MANIM_PYTHON")
    if env and Path(env).exists():
        return env
    if importlib.util.find_spec("manim") is not None:
        return sys.executable
    repo_root = Path(__file__).resolve().parents[3]
    for base in (Path.cwd(), repo_root):
        cand = base / ".manim-env"
        if (cand / "bin" / "manim").exists():
            return str(cand / "bin" / "python")
    return None


def manim_available() -> bool:
    return _manim_python() is not None


def write_manim_scene(scene: list[dict], title: str, problem_id: str, out_path) -> str:
    out_path = Path(out_path)
    lo, hi = scene_mod.bounds(scene)
    center = (lo + hi) / 2.0
    span = max(hi - lo, 1e-6)
    scale = max(0.5, min(4.0, 4.4 / span))
    code = (
        _TEMPLATE.replace("__PROBLEM_ID__", problem_id)
        .replace("__FILE_NAME__", out_path.name)
        .replace("__SCENE_JSON__", json.dumps(scene))
        .replace("__TITLE__", repr(title))
        .replace("__CENTER__", repr([center, center, center]))
        .replace("__SCALE__", repr(round(scale, 4)))
    )
    out_path.write_text(code)
    return str(out_path)


def try_render_manim(
    scene_path, still: bool = True, quality: str = "l", timeout: int = 600
) -> tuple[bool, str, list[str]]:
    """Best-effort render. Returns (ok, message, produced files)."""
    scene_path = Path(scene_path)
    python = _manim_python()
    if python is None:
        return False, "manim not installed (see README: micromamba .manim-env); scene file written for later", []
    media_dir = scene_path.parent / "media"
    cmd = [python, "-m", "manim", "render"]
    if still:
        cmd.append("-s")
    cmd += [f"-q{quality}", "--media_dir", str(media_dir), str(scene_path), "ConjectureScene"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return False, f"manim render timed out after {timeout}s", []
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-8:]
        return False, "manim render failed: " + " / ".join(tail), []
    want = ".png" if still else ".mp4"
    produced = sorted(
        str(p)
        for p in media_dir.rglob(f"*{want}")
        if p.is_file() and "partial_movie_files" not in p.parts
    )
    return True, "manim render ok", produced
